### ISSUE TITLE
DateUtils - modify

### ISSUE THREAD

**Issue by LottaJohnsson** [LottaJohnsson/commons-lang#5]

**Comment by Tian0602** [comment]
25 (based on CFG V = E - N + 2*P and view exception as an end)
[timeModifyCFG.pdf](https://github.com/LottaJohnsson/commons-lang/files/14330082/timeModifyCFG.pdf)

**Comment by Tian0602** [comment]
32 (based on the CFG with couting the boolean expression additionally and view exception as an end)
[timeModifyCFG.pdf](https://github.com/LottaJohnsson/commons-lang/files/14331319/timeModifyCFG.pdf)
