### ISSUE TITLE
StrSubstitutor - substitute

### ISSUE THREAD

**Issue by LottaJohnsson** [LottaJohnsson/commons-lang#6]

**Comment by Tian0602** [comment]
22 (based on the CFG with couting the boolean expression additionally, and an important thing is that "return altered ? 1 : 0" should be seen as equal to "if-else" then count)
[substituteCFG.pdf](https://github.com/LottaJohnsson/commons-lang/files/14331348/substituteCFG.pdf)

**Comment by filippanilsson** [comment]
22 = 21-1+2
(21 decisions, 1 exit point)
